"""The migration chain itself: it must upgrade from empty, match the models exactly, and
downgrade back cleanly — on a scratch database of its own, separate from the seeded one."""

import asyncio

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import NullPool

from tests.db.conftest import TEST_DATABASE_URL, alembic_config, recreate_database

SCRATCH_URL = (
    make_url(TEST_DATABASE_URL)
    .set(database=f"{make_url(TEST_DATABASE_URL).database}_migrations")
    .render_as_string(hide_password=False)
)


async def _tables(url: str) -> set[str]:
    engine = create_async_engine(url, poolclass=NullPool)
    async with engine.connect() as conn:
        rows = await conn.execute(
            text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        )
        names = {r[0] for r in rows}
    await engine.dispose()
    return names


@pytest.fixture(scope="module")
def scratch_url():
    asyncio.run(recreate_database(SCRATCH_URL))
    return SCRATCH_URL


def test_upgrade_matches_models_and_downgrades_cleanly(scratch_url):
    cfg = alembic_config(scratch_url)
    command.upgrade(cfg, "head")
    assert "fact_check_reports" in asyncio.run(_tables(scratch_url))

    # Same check CI runs as `alembic check`: a model change without a migration fails here.
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"Models and migrations have drifted:\n{exc}")

    command.downgrade(cfg, "base")
    assert asyncio.run(_tables(scratch_url)) == {"alembic_version"}

    command.upgrade(cfg, "head")  # and back up again from a downgraded database
    assert "audit_log" in asyncio.run(_tables(scratch_url))
