"""Initial P3 schema: every table from docs/adr/0002-p3-backend-and-database.md §2.

Autogenerated from app/db/models/, then extended by hand with what autogenerate can't see:
the `vector` and `pg_trgm` extensions, the report-id sequence and the audit log's
append-only trigger.

Revision ID: 0001
Revises:
Create Date: 2026-09-23 06:25:28.064119
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector for fact_check_reports.embedding (FR-SEARCH-03); pg_trgm for fuzzy title search.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "model_evaluations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_evaluations")),
    )
    op.create_index(
        op.f("ix_model_evaluations_metric"), "model_evaluations", ["metric"], unique=False
    )
    op.create_table(
        "trusted_sources",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("languages", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_crawled", sa.DateTime(timezone=True), nullable=True),
        sa.Column("crawl_ok", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('media', 'government', 'fact-checker', 'international', 'academic')",
            name=op.f("ck_trusted_sources_type"),
        ),
        sa.CheckConstraint("tier BETWEEN 1 AND 3", name=op.f("ck_trusted_sources_tier")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trusted_sources")),
        sa.UniqueConstraint("domain", name=op.f("uq_trusted_sources_domain")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), server_default="public", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("preferred_language", sa.Text(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column(
            "two_factor_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "preferred_language IS NULL OR preferred_language IN ('en', 'lg', 'ach', 'nyn', 'teo')",
            name=op.f("ck_users_preferred_language"),
        ),
        sa.CheckConstraint(
            "role IN ('public', 'journalist', 'expert', 'admin')", name=op.f("ck_users_role")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'pending')", name=op.f("ck_users_status")
        ),
        sa.CheckConstraint(
            "email IS NOT NULL OR phone IS NOT NULL", name=op.f("ck_users_has_identifier")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_table(
        "accreditation_applications",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.Column("document_key", sa.Text(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_id", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_accreditation_applications_status"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_accreditation_applications_reviewer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_accreditation_applications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accreditation_applications")),
    )
    op.create_index(
        op.f("ix_accreditation_applications_user_id"),
        "accreditation_applications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_accreditation_applications_pending_user",
        "accreditation_applications",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "alert_settings",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alert_settings_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_alert_settings")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("prefix", sa.Text(), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scopes <@ ARRAY['submit','read']::text[]", name=op.f("ck_api_keys_scopes")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("secret_hash", name=op.f("uq_api_keys_secret_hash")),
    )
    op.create_index(op.f("ix_api_keys_prefix"), "api_keys", ["prefix"], unique=False)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.Text(), nullable=True),
        sa.Column("actor_name", sa.Text(), nullable=False),
        sa.Column("actor_role", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.Column("ip", sa.Text(), server_default="", nullable=False),
        sa.CheckConstraint(
            "action IN ('verdict.override', 'verdict.confirm', 'user.role_change', 'user.suspend', 'source.add', 'source.deactivate', 'broadcast.send', 'settings.update', 'moderation.remove')",
            name=op.f("ck_audit_log_action"),
        ),
        sa.CheckConstraint(
            "actor_role IN ('public', 'journalist', 'expert', 'admin')",
            name=op.f("ck_audit_log_actor_role"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index("ix_audit_log_at", "audit_log", [sa.literal_column("at DESC")], unique=False)
    op.create_table(
        "auth_challenges",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("pending_signup", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("channel IN ('sms', 'email')", name=op.f("ck_auth_challenges_channel")),
        sa.CheckConstraint(
            "purpose IN ('signup', 'two_factor', 'password_reset')",
            name=op.f("ck_auth_challenges_purpose"),
        ),
        sa.CheckConstraint(
            "user_id IS NOT NULL OR pending_signup IS NOT NULL",
            name=op.f("ck_auth_challenges_has_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_challenges_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_challenges")),
    )
    op.create_index(
        op.f("ix_auth_challenges_user_id"), "auth_challenges", ["user_id"], unique=False
    )
    op.create_table(
        "broadcasts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("channels", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("sent_by", sa.Text(), nullable=False),
        sa.Column("reach", sa.Integer(), server_default="0", nullable=False),
        sa.Column("opened", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("severity IN ('high', 'critical')", name=op.f("ck_broadcasts_severity")),
        sa.ForeignKeyConstraint(
            ["sent_by"], ["users.id"], name=op.f("fk_broadcasts_sent_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcasts")),
    )
    op.create_table(
        "oauth_identities",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('google', 'facebook')", name=op.f("ck_oauth_identities_provider")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_oauth_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_identities")),
        sa.UniqueConstraint(
            "provider", "subject", name=op.f("uq_oauth_identities_provider_subject")
        ),
    )
    op.create_index(
        op.f("ix_oauth_identities_user_id"), "oauth_identities", ["user_id"], unique=False
    )
    op.create_table(
        "platform_settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_platform_settings_singleton")),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_platform_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_settings")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("device", sa.Text(), nullable=False),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "api_usage_hourly",
        sa.Column("api_key_id", sa.Text(), nullable=False),
        sa.Column("hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_api_usage_hourly_api_key_id_api_keys")
        ),
        sa.PrimaryKeyConstraint("api_key_id", "hour", name=op.f("pk_api_usage_hourly")),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("href", sa.Text(), nullable=True),
        sa.Column("broadcast_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('verdict-ready', 'topic-alert', 'review-outcome', 'broadcast', 'accreditation')",
            name=op.f("ck_notifications_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_notifications_broadcast_id_broadcasts"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("tracking_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("api_key_id", sa.Text(), nullable=True),
        sa.Column("channel", sa.Text(), server_default="web", nullable=False),
        sa.Column("channel_ref", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("article_url", sa.Text(), nullable=True),
        sa.Column("media_object_key", sa.Text(), nullable=True),
        sa.Column("media_content_type", sa.Text(), nullable=True),
        sa.Column("media_bytes", sa.Integer(), nullable=True),
        sa.Column("language", sa.Text(), server_default="auto", nullable=False),
        sa.Column("preview", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column(
            "steps",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "channel IN ('web', 'partner', 'whatsapp', 'telegram')",
            name=op.f("ck_submissions_channel"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'completed', 'failed')",
            name=op.f("ck_submissions_status"),
        ),
        sa.CheckConstraint(
            "tracking_id ~ '^ZL-[A-Z2-9]{4}-[A-Z2-9]{2}$'", name=op.f("ck_submissions_tracking_id")
        ),
        sa.CheckConstraint(
            "type IN ('text', 'url', 'media', 'article')", name=op.f("ck_submissions_type")
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_submissions_api_key_id_api_keys")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_submissions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("tracking_id", name=op.f("pk_submissions")),
    )
    op.create_index(op.f("ix_submissions_api_key_id"), "submissions", ["api_key_id"], unique=False)
    op.create_index(op.f("ix_submissions_user_id"), "submissions", ["user_id"], unique=False)
    op.create_index(
        "uq_submissions_api_key_idempotency",
        "submissions",
        ["api_key_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("api_key_id IS NOT NULL AND idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "uq_submissions_user_idempotency",
        "submissions",
        ["user_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL AND idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "fact_check_reports",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tracking_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("submitted_text", sa.Text(), server_default="", nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_host", sa.Text(), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "what_is_false",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "what_is_true",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "claims",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "ai_signals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_seconds", sa.Float(), nullable=False),
        sa.Column("human_review", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("accurate_public", sa.Integer(), server_default="0", nullable=False),
        sa.Column("accurate_journalist", sa.Integer(), server_default="0", nullable=False),
        sa.Column("accurate_expert", sa.Integer(), server_default="0", nullable=False),
        sa.Column("inaccurate_public", sa.Integer(), server_default="0", nullable=False),
        sa.Column("inaccurate_journalist", sa.Integer(), server_default="0", nullable=False),
        sa.Column("inaccurate_expert", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ccs", sa.Integer(), nullable=True),
        sa.Column("community_status", sa.Text(), server_default="standard", nullable=False),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple'::regconfig, coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(category, '') || ' ' || coalesce(submitted_text, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "community_status IN ('verified', 'standard', 'questioned', 'escalated', 'suspended')",
            name=op.f("ck_fact_check_reports_community_status"),
        ),
        sa.CheckConstraint(
            "content_type IN ('text', 'url', 'image', 'audio', 'video')",
            name=op.f("ck_fact_check_reports_content_type"),
        ),
        sa.CheckConstraint(
            "verdict IN ('authentic', 'likely-false', 'false', 'ai-generated', 'unverifiable')",
            name=op.f("ck_fact_check_reports_verdict"),
        ),
        sa.CheckConstraint(
            "ccs IS NULL OR ccs BETWEEN 0 AND 100", name=op.f("ck_fact_check_reports_ccs")
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 100", name=op.f("ck_fact_check_reports_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["tracking_id"],
            ["submissions.tracking_id"],
            name=op.f("fk_fact_check_reports_tracking_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_check_reports")),
        sa.UniqueConstraint("tracking_id", name=op.f("uq_fact_check_reports_tracking_id")),
    )
    op.create_index(
        op.f("ix_fact_check_reports_category"), "fact_check_reports", ["category"], unique=False
    )
    op.create_index(
        "ix_fact_check_reports_checked_at",
        "fact_check_reports",
        [sa.literal_column("checked_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_check_reports_community_status"),
        "fact_check_reports",
        ["community_status"],
        unique=False,
    )
    op.create_index(
        "ix_fact_check_reports_search_tsv",
        "fact_check_reports",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_fact_check_reports_source_host"),
        "fact_check_reports",
        ["source_host"],
        unique=False,
    )
    op.create_index(
        "ix_fact_check_reports_title_trgm",
        "fact_check_reports",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_fact_check_reports_verdict"), "fact_check_reports", ["verdict"], unique=False
    )
    op.create_table(
        "content_reports",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("sample", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "reported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "resolution IS NULL OR resolution IN ('dismiss', 'remove')",
            name=op.f("ck_content_reports_resolution"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_content_reports_report_id_fact_check_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name=op.f("fk_content_reports_resolved_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_reports")),
    )
    op.create_index(
        op.f("ix_content_reports_report_id"), "content_reports", ["report_id"], unique=False
    )
    op.create_index(
        "uq_content_reports_open_report",
        "content_reports",
        ["report_id"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "expert_annotations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Text(), nullable=False),
        sa.Column("author_title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_expert_annotations_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_expert_annotations_report_id_fact_check_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expert_annotations")),
    )
    op.create_index(
        op.f("ix_expert_annotations_report_id"), "expert_annotations", ["report_id"], unique=False
    )
    op.create_table(
        "manipulation_signals",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("accounts", sa.Integer(), nullable=False),
        sa.Column("window", sa.Text(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "direction IN ('accurate', 'inaccurate')",
            name=op.f("ck_manipulation_signals_direction"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_manipulation_signals_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_manipulation_signals_report_id_fact_check_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manipulation_signals")),
    )
    op.create_index(
        op.f("ix_manipulation_signals_report_id"),
        "manipulation_signals",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "rating_comments",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("vote", sa.Text(), nullable=False),
        sa.Column("rater_role", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_by", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "rater_role IN ('public', 'journalist', 'expert')",
            name=op.f("ck_rating_comments_rater_role"),
        ),
        sa.CheckConstraint(
            "vote IN ('accurate', 'inaccurate')", name=op.f("ck_rating_comments_vote")
        ),
        sa.ForeignKeyConstraint(
            ["removed_by"], ["users.id"], name=op.f("fk_rating_comments_removed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_rating_comments_report_id_fact_check_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_rating_comments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_comments")),
    )
    op.create_index(
        "ix_rating_comments_report_created",
        "rating_comments",
        ["report_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_rating_comments_user_id"), "rating_comments", ["user_id"], unique=False
    )
    op.create_table(
        "ratings",
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("vote", sa.Text(), nullable=False),
        sa.Column("rater_role", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("excluded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "rater_role IN ('public', 'journalist', 'expert')", name=op.f("ck_ratings_rater_role")
        ),
        sa.CheckConstraint("vote IN ('accurate', 'inaccurate')", name=op.f("ck_ratings_vote")),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_ratings_report_id_fact_check_reports"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_ratings_user_id_users")),
        sa.PrimaryKeyConstraint("report_id", "user_id", name=op.f("pk_ratings")),
    )
    op.create_index(op.f("ix_ratings_user_id"), "ratings", ["user_id"], unique=False)
    op.create_table(
        "content_flags",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("content_report_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_report_id"],
            ["content_reports.id"],
            name=op.f("fk_content_flags_content_report_id_content_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_content_flags_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_flags")),
        sa.UniqueConstraint(
            "content_report_id", "user_id", name=op.f("uq_content_flags_content_report_id_user_id")
        ),
    )
    op.create_index(
        op.f("ix_content_flags_content_report_id"),
        "content_flags",
        ["content_report_id"],
        unique=False,
    )
    op.create_index(op.f("ix_content_flags_user_id"), "content_flags", ["user_id"], unique=False)
    op.create_table(
        "review_cases",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "flagged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_report_id", sa.Text(), nullable=True),
        sa.Column("assignee_id", sa.Text(), nullable=True),
        sa.Column("priority", sa.Text(), server_default="normal", nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("priority IN ('normal', 'high')", name=op.f("ck_review_cases_priority")),
        sa.CheckConstraint(
            "reason IN ('community-escalation', 'suspended', 'user-reports', 'low-confidence')",
            name=op.f("ck_review_cases_reason"),
        ),
        sa.CheckConstraint("status IN ('open', 'decided')", name=op.f("ck_review_cases_status")),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.id"], name=op.f("fk_review_cases_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["content_report_id"],
            ["content_reports.id"],
            name=op.f("fk_review_cases_content_report_id_content_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_review_cases_report_id_fact_check_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_cases")),
    )
    op.create_index(
        op.f("ix_review_cases_assignee_id"), "review_cases", ["assignee_id"], unique=False
    )
    op.create_index(op.f("ix_review_cases_report_id"), "review_cases", ["report_id"], unique=False)
    op.create_index(op.f("ix_review_cases_status"), "review_cases", ["status"], unique=False)
    op.create_index(
        "uq_review_cases_open_report",
        "review_cases",
        ["report_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("case_id", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("from_verdict", sa.Text(), nullable=False),
        sa.Column("to_verdict", sa.Text(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("reviewer_id", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("turnaround_hours", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "from_verdict IN ('authentic', 'likely-false', 'false', 'ai-generated', 'unverifiable')",
            name=op.f("ck_review_decisions_from_verdict"),
        ),
        sa.CheckConstraint(
            "outcome IN ('confirmed', 'overridden')", name=op.f("ck_review_decisions_outcome")
        ),
        sa.CheckConstraint(
            "to_verdict IN ('authentic', 'likely-false', 'false', 'ai-generated', 'unverifiable')",
            name=op.f("ck_review_decisions_to_verdict"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["review_cases.id"], name=op.f("fk_review_decisions_case_id_review_cases")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["fact_check_reports.id"],
            name=op.f("fk_review_decisions_report_id_fact_check_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_review_decisions_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
        sa.UniqueConstraint("case_id", name=op.f("uq_review_decisions_case_id")),
    )
    op.create_index(
        op.f("ix_review_decisions_report_id"), "review_decisions", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_decisions_reviewer_id"), "review_decisions", ["reviewer_id"], unique=False
    )

    # New reports are numbered fc-YYYY-NNNN from this (app/db/ids.py). The seed moves it past
    # the sample reports' numbers.
    op.execute("CREATE SEQUENCE fact_check_report_number_seq")

    # FR-ADMIN-07: the audit log is append-only. A trigger rather than only REVOKE, because it
    # also binds the table owner and superusers (the role migrations and CI connect as).
    op.execute(
        """
        CREATE FUNCTION audit_log_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (% is not allowed)', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    op.execute("DROP SEQUENCE IF EXISTS fact_check_report_number_seq")
    op.drop_index(op.f("ix_review_decisions_reviewer_id"), table_name="review_decisions")
    op.drop_index(op.f("ix_review_decisions_report_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index(
        "uq_review_cases_open_report",
        table_name="review_cases",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_review_cases_status"), table_name="review_cases")
    op.drop_index(op.f("ix_review_cases_report_id"), table_name="review_cases")
    op.drop_index(op.f("ix_review_cases_assignee_id"), table_name="review_cases")
    op.drop_table("review_cases")
    op.drop_index(op.f("ix_content_flags_user_id"), table_name="content_flags")
    op.drop_index(op.f("ix_content_flags_content_report_id"), table_name="content_flags")
    op.drop_table("content_flags")
    op.drop_index(op.f("ix_ratings_user_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_rating_comments_user_id"), table_name="rating_comments")
    op.drop_index("ix_rating_comments_report_created", table_name="rating_comments")
    op.drop_table("rating_comments")
    op.drop_index(op.f("ix_manipulation_signals_report_id"), table_name="manipulation_signals")
    op.drop_table("manipulation_signals")
    op.drop_index(op.f("ix_expert_annotations_report_id"), table_name="expert_annotations")
    op.drop_table("expert_annotations")
    op.drop_index(
        "uq_content_reports_open_report",
        table_name="content_reports",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_index(op.f("ix_content_reports_report_id"), table_name="content_reports")
    op.drop_table("content_reports")
    op.drop_index(op.f("ix_fact_check_reports_verdict"), table_name="fact_check_reports")
    op.drop_index(
        "ix_fact_check_reports_title_trgm",
        table_name="fact_check_reports",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_fact_check_reports_source_host"), table_name="fact_check_reports")
    op.drop_index(
        "ix_fact_check_reports_search_tsv", table_name="fact_check_reports", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_fact_check_reports_community_status"), table_name="fact_check_reports")
    op.drop_index("ix_fact_check_reports_checked_at", table_name="fact_check_reports")
    op.drop_index(op.f("ix_fact_check_reports_category"), table_name="fact_check_reports")
    op.drop_table("fact_check_reports")
    op.drop_index(
        "uq_submissions_user_idempotency",
        table_name="submissions",
        postgresql_where=sa.text("user_id IS NOT NULL AND idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_submissions_api_key_idempotency",
        table_name="submissions",
        postgresql_where=sa.text("api_key_id IS NOT NULL AND idempotency_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_submissions_user_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_api_key_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("api_usage_hourly")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("platform_settings")
    op.drop_index(op.f("ix_oauth_identities_user_id"), table_name="oauth_identities")
    op.drop_table("oauth_identities")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_auth_challenges_user_id"), table_name="auth_challenges")
    op.drop_table("auth_challenges")
    op.drop_index("ix_audit_log_at", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_prefix"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("alert_settings")
    op.drop_index(
        "uq_accreditation_applications_pending_user",
        table_name="accreditation_applications",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        op.f("ix_accreditation_applications_user_id"), table_name="accreditation_applications"
    )
    op.drop_table("accreditation_applications")
    op.drop_table("users")
    op.drop_table("trusted_sources")
    op.drop_index(op.f("ix_model_evaluations_metric"), table_name="model_evaluations")
    op.drop_table("model_evaluations")
